### ISSUE TITLE
AttributeError AttributeError: 'NoneType' object has no attribute 'drivername'

### ISSUE THREAD

**Issue by j-yeskay** [keerthisree-raghu/TechTalk#1]
had to make the following change in config.py to get this app working on my windows 10 machine

![before](https://user-images.githubusercontent.com/65070442/120442331-1a1b1480-c3a3-11eb-9bd2-e4062b78da6b.jpg)

![after](https://user-images.githubusercontent.com/65070442/120442380-2a32f400-c3a3-11eb-85d5-7cd82db179a8.jpg)

**Comment by keerthisree-raghu** [comment]
Yes, that is an environment variable. It is meant to be a placeholder for your database URI. You can either set the URI in the config.py file or use it directly the way you have.
